language: none

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

before_install:
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install build-essential libgl1-mesa-dev ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -yy install qtbase5-dev ; fi


before_script:
  - ./download_third_party.sh 1>download_log.txt
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make 1>build_log.txt
  - tail -n 100 build_log.txt

notifications:
  email: false
