language: none

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

before_install:
   - sudo apt-get update -qq

before_script:
  - ./download_third_party.sh 1>download_log.txt
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make 1>build_log.txt
  - cd ../examples/hello_world
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../../complex_type
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../../inheritance
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../../visitor
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../../http
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../../db_client
  - mkdir build
  - cd build
  - cmake ..
  - make

notifications:
  email: false
