language: none

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env: CXX=g++-5 CC=gcc-5 QT=5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

git:
  depth: 10

before_install:
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install build-essential libgl1-mesa-dev ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -yy install qtbase5-dev ; fi


build: make

script:
  - mkdir build
  - cd build
  - cmake .. && make -j

notifications:
  email: false
